### ISSUE TITLE
ဥ◌်း ရေးလို့မရပါ

### ISSUE THREAD

**Issue by myoheinapp** [thantthet/keymagic-keyboards#1]
စဥ◌်းစား ပုစဥ◌်း ရေးရင် ငသတ်က ဥအပေါ်မှာမပေါ်နေပါ

**Comment by khunmk** [comment]
ဉ + ််  + း 

N + f + ;

**Comment by kaungkyawlin** [comment]
'စဉ်းစား' နဲ့ 'ပုစဉ်း' ကိုရေးရာမှာ စလုံး ကို 'ဉ  ကလေး'နဲ့ သတ်တာပါ။ အက္ခရာ 'ဥ' နဲ့သတ်တာမဟုတ်ပါဘူး။
ဒါကြောင့် 'စဉ်း' ရေးရာမှာ  

      စ  +  ဉ  +  ် + း    
      p  +  N  +  f + ;

လို့ရေးရပါမယ်။
