### ISSUE TITLE
Pyidaungsu MM keyboard issue with ဥ + ီ key combination

### ISSUE THREAD

**Issue by Acodevel** [thantthet/keymagic-keyboards#6]
While typing the two together, it results ဥ◌ီ
Using on Mac OS running Key Magic 1.5.5.

**Comment by thantthet** [comment]
You have to use Shift+M
ပြည်ထောင်စု လက်ကွက်ရိုက်နည်း: https://unicodetoday.org/keyboard/2019/03/05/pyidaungsu-mm-typing.html
