### ISSUE TITLE
စာလုံးနှစ်လုံးဆင့်ကိုဇောက်ကု​ဒ်မှာဘ​ယ်လိုရေးလဲ

### ISSUE THREAD

**Issue by david-gnext** [thantthet/keymagic-keyboards#7]
ဥပမာ `ဒုက္ခ​` လို့ရေးချင်ရင်ဘယ်လိုရေးရလဲ။  shift + f + keyname နဲ့တွဲရိုက်လည်းမရဘူး။

<img width="235" alt="Screen Shot 2020-12-10 at 22 57 52" src="https://user-images.githubusercontent.com/3381999/101781469-313b2100-3b3b-11eb-9f06-ef7ea43fe8cd.png">

**Comment by thantthet** [comment]
Typing with **~** + Key. for က္ခ. Type **~** follow by **c**

![](https://4.bp.blogspot.com/-sK1LT21AK-k/WZ2UJOWQyAI/AAAAAAAAS9c/VBofzyTBKH4Nm2EpBhRkCv46nJWmiUJHgCLcBGAs/s1600/AlphaZawgyi.jpg)

**Comment by david-gnext** [comment]
Not okay ! I also forget to mention that it's for Mac
